### ISSUE TITLE
Issue on globe background color

### ISSUE THREAD

**Issue by arifmuftiweavers** [janarosmonaliev/pandemic-globe#3]
Hello Sir,
 I have used your globe canvas but I can change the tv.background colo could you please help me to change background color.
 thanks

**Comment by janarosmonaliev** [comment]
Hi @arifmuftiweavers !

Background color can be set by assigning a color to `background` property of the `scene`.
Please note that `Ambient Light` also affects the shade of the color.

Here's an code snippet:
```javascript
// Initialize scene, light
  scene = new Scene();
  scene.add(new AmbientLight(0xbbbbbb, 0.3));
  scene.background = new Color(0x040d21);
```

**Comment by arifmuftiweavers** [comment]
it's not working from my end  when I used this code it says 
index.html:32 Uncaught ReferenceError: Scene is not defined
also which type of color code should I use there it's a hex color code or rgba color code. as per the mentioned color code it's, not a hex code or rgba code.

please find my attachment please.


[github-globe-main.zip](https://github.com/janarosmonaliev/github-globe/files/7836927/github-globe-main.zip)
